### ISSUE TITLE
Deprecation SQL Alchemy warning

### ISSUE THREAD

**Issue by skolchin** [skolchin/astro-extras#2]
At test_table.py, 141:

![image](https://github.com/skolchin/astro-extras/assets/37234150/4ecef79c-4e7b-4316-ad36-1472158d73e7)

**Comment by Denis-Pashkov** [comment]
This was fixed in the commit: https://github.com/skolchin/astro-extras/commit/01d609322861d196ddf00c28c31aedd9ee7c5823.

**Comment by Denis-Pashkov** [comment]
This was fixed in the commit: https://github.com/skolchin/astro-extras/commit/01d609322861d196ddf00c28c31aedd9ee7c5823.
